import JSZip from 'jszip';
import type { BinderDocument, BinderSection } from '../rendering/binderDocument';

const safeSegment = (value: string) => value.normalize('NFKC').split('').filter((character) => { const code = character.charCodeAt(0); return character !== '/' && character !== '\\' && code >= 32 && code !== 127; }).join('').replace(/[^\p{L}\p{N}._ -]/gu, '_').trim().slice(0, 80) || 'section';
const escapeHtml = (value: string) => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
const escapeMarkdown = (value: string) => value.replaceAll('\\', '\\\\').replaceAll('`', '\\`').replaceAll('*', '\\*').replaceAll('_', '\\_').replaceAll('[', '\\[').replaceAll(']', '\\]').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
const sectionHtml = (section: BinderSection) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${escapeHtml(section.title)}</title><link rel="stylesheet" href="../styles/binder.css"></head><body><main><h1>${escapeHtml(section.title)}</h1>${section.blocks.map((block) => block.type === 'pageBreak' ? '<div class="page-break" aria-hidden="true"></div>' : `<p>${escapeHtml(String(block.text ?? ''))}</p>`).join('')}</main></body></html>`;
const sectionMarkdown = (section: BinderSection) => `---\nsection: ${safeSegment(section.id)}\n---\n\n# ${escapeMarkdown(section.title)}\n\n${section.blocks.map((block) => block.type === 'pageBreak' ? '\\pagebreak' : escapeMarkdown(String(block.text ?? ''))).join('\n\n')}\n`;
const digest = async (value: string) => { const bytes = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value)); return btoa(String.fromCharCode(...new Uint8Array(bytes))); };

export async function exportReadableArchive(document: BinderDocument, locale: string, householdName = '') { const root = `Continuity-Binder-${new Date().toISOString().slice(0, 10)}`; const zip = new JSZip(); const files: Record<string, string> = {}; const css = 'body{color:#1f252b;background:#fff;font-family:Georgia,"Times New Roman",serif;line-height:1.45;max-width:900px;margin:0 auto;padding:32px}h1{font-size:28pt}'; files['styles/binder.css'] = css; const links: string[] = []; document.sections.forEach((section, index) => { const stem = `${String(index).padStart(2, '0')}-${safeSegment(section.id)}`; const htmlPath = `html/${stem}.html`; const markdownPath = `markdown/${stem}.md`; files[htmlPath] = sectionHtml(section); files[markdownPath] = sectionMarkdown(section); links.push(`<li><a href="${htmlPath}">${escapeHtml(section.title)}</a></li>`); }); const timestamp = document.metadata.generatedAt; files['README.html'] = `<!doctype html><meta charset="utf-8"><title>Continuity Binder archive</title><p>Readable offline archive. Generated ${escapeHtml(timestamp)}.</p>`; files['index.html'] = `<!doctype html><html><head><meta charset="utf-8"><title>Continuity Binder</title><link rel="stylesheet" href="styles/binder.css"></head><body><main><h1>Continuity Binder</h1>${householdName ? `<p>${escapeHtml(householdName)}</p>` : ''}<p>Exported ${escapeHtml(timestamp)}</p><p>Privacy warning: this archive is readable without your passphrase. Store it securely.</p><ol>${links.join('')}</ol></main></body></html>`; const manifest: Record<string, unknown> = { exportFormatVersion: 1, applicationVersion: '0.1.0', dataSchemaVersion: document.metadata.schemaVersion, generatedAt: timestamp, locale, includedSectionIds: document.sections.map((section) => section.id), checksums: {} }; for (const [path, content] of Object.entries(files)) (manifest.checksums as Record<string, string>)[path] = await digest(content); files['manifest.json'] = JSON.stringify(manifest, null, 2); Object.entries(files).forEach(([path, content]) => zip.file(`${root}/${path}`, content)); return zip.generateAsync({ type: 'blob' }); }
