import { useEffect, useState, type FormEvent } from 'react';
import { useTranslation } from 'react-i18next';
import { z } from 'zod';
import { SelectField, TextArea, TextField } from '../../components/forms';
import { createEncryptedRepository, type ContinuityDatabase } from '../../data/repositories/encryptedRepository';

const base = { id: z.string(), schemaVersion: z.number(), createdAt: z.string(), updatedAt: z.string() };
export const claimsBenefitsSchema = z.object({ ...base, benefitPolicy: z.string(), carrier: z.string(), claimContact: z.string(), documentsRequested: z.string(), estimatedBenefit: z.string(), submissionMethod: z.string(), followUpContact: z.string(), notes: z.string(), printPolicy: z.enum(['full', 'last4', 'hidden']), includeInPrint: z.boolean(), includeInReadableExport: z.boolean() });
type Claim = z.infer<typeof claimsBenefitsSchema>;
type FormState = Omit<Claim, 'id' | 'schemaVersion' | 'createdAt' | 'updatedAt'>;
const empty = { benefitPolicy: '', carrier: '', claimContact: '', documentsRequested: '', estimatedBenefit: '', submissionMethod: '', followUpContact: '', notes: '', printPolicy: 'hidden' as const, includeInPrint: true, includeInReadableExport: true };

export function ClaimsBenefitsTracker({ database, dek }: { database: ContinuityDatabase | null; dek: CryptoKey }) {
  const { t } = useTranslation('v2', { keyPrefix: 'claims_benefits_tracker' });
  const [records, setRecords] = useState<Claim[]>([]); const [form, setForm] = useState<FormState>(empty); const [saved, setSaved] = useState(false);
  const load = () => { if (!database) return; void createEncryptedRepository(database, dek, 'ClaimsBenefitsRecord', claimsBenefitsSchema).list().then(setRecords); };
  useEffect(load, [database, dek]);
  const save = async (event: FormEvent) => { event.preventDefault(); if (!database || !form.benefitPolicy.trim() || !form.carrier.trim()) return; const now = new Date().toISOString(); await createEncryptedRepository(database, dek, 'ClaimsBenefitsRecord', claimsBenefitsSchema).put({ id: crypto.randomUUID(), schemaVersion: 1, createdAt: now, updatedAt: now, ...form, benefitPolicy: form.benefitPolicy.trim(), carrier: form.carrier.trim() }); setForm(empty); setSaved(true); load(); };
  return <section className="section-page v2-feature"><p className="eyebrow">{t('title')}</p><h2>{t('title')}</h2><p>{t('intro')}</p><p className="security-clarification">{t('caution')}</p><div className="section-card"><h3>{t('summary')}</h3>{records.length === 0 ? <p>{t('empty')}</p> : <ul>{records.map((record) => <li key={record.id}>{record.benefitPolicy} — {record.carrier}</li>)}</ul>}</div><div className="section-card"><h3>{t('add')}</h3><form onSubmit={(event) => void save(event)}><div className="form-grid"><TextField label={t('benefitPolicy')} value={form.benefitPolicy} onChange={(event) => setForm({ ...form, benefitPolicy: event.target.value })} required /><TextField label={t('carrier')} value={form.carrier} onChange={(event) => setForm({ ...form, carrier: event.target.value })} required /><TextField label={t('claimContact')} value={form.claimContact} onChange={(event) => setForm({ ...form, claimContact: event.target.value })} /><TextField label={t('estimatedBenefit')} value={form.estimatedBenefit} onChange={(event) => setForm({ ...form, estimatedBenefit: event.target.value })} /><TextField label={t('submissionMethod')} value={form.submissionMethod} onChange={(event) => setForm({ ...form, submissionMethod: event.target.value })} /><TextField label={t('followUpContact')} value={form.followUpContact} onChange={(event) => setForm({ ...form, followUpContact: event.target.value })} /></div><TextArea label={t('documentsRequested')} value={form.documentsRequested} onChange={(event) => setForm({ ...form, documentsRequested: event.target.value })} /><TextArea label={t('notes')} value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /><SelectField label={t('printPolicy')} value={form.printPolicy} onChange={(event) => setForm({ ...form, printPolicy: event.target.value as Claim['printPolicy'] })} options={(['full', 'last4', 'hidden'] as const).map((value) => ({ value, label: t(value) }))} /><label><input type="checkbox" checked={form.includeInPrint} onChange={(event) => setForm({ ...form, includeInPrint: event.target.checked })} /> {t('includeInPrint')}</label><label><input type="checkbox" checked={form.includeInReadableExport} onChange={(event) => setForm({ ...form, includeInReadableExport: event.target.checked })} /> {t('includeInReadableExport')}</label><button className="button button-primary">{t('save')}</button>{saved && <p role="status">{t('saved')}</p>}</form></div><div className="section-card paper-actions"><h3>{t('paperActions')}</h3><p>☐ {t('claimOpened')} ☐ {t('documentsSupplied')} ☐ {t('approved')} ☐ {t('paid')} ☐ {t('closed')}</p><p>{t('date')}: ____ / ____ / ______  {t('reference')}: __________</p></div></section>;
}
