import { useEffect, useState, type FormEvent } from 'react';
import { useTranslation } from 'react-i18next';
import { z } from 'zod';
import { SelectField, TextArea, TextField } from '../../components/forms';
import { personSchema } from '../household/HouseholdSetup';
import { createEncryptedRepository, type ContinuityDatabase } from '../../data/repositories/encryptedRepository';

const base = { id: z.string(), schemaVersion: z.number(), createdAt: z.string(), updatedAt: z.string() };
export const deathCertificateSchema = z.object({ ...base, deceasedPersonId: z.string(), copiesOrdered: z.string(), orderingOffice: z.string(), orderDate: z.string(), copiesReceived: z.string(), institution: z.string(), copySent: z.string(), returnExpected: z.string(), referenceNumber: z.string(), notes: z.string(), includeInPrint: z.boolean(), includeInReadableExport: z.boolean() });
type RecordType = z.infer<typeof deathCertificateSchema>;
type Person = z.infer<typeof personSchema>;
const empty = { deceasedPersonId: '', copiesOrdered: '', orderingOffice: '', orderDate: '', copiesReceived: '', institution: '', copySent: '', returnExpected: '', referenceNumber: '', notes: '', includeInPrint: true, includeInReadableExport: true };

export function DeathCertificateTracker({ database, dek }: { database: ContinuityDatabase | null; dek: CryptoKey }) {
  const { t } = useTranslation('v2', { keyPrefix: 'death_certificate_tracker' });
  const [records, setRecords] = useState<RecordType[]>([]); const [people, setPeople] = useState<Person[]>([]); const [form, setForm] = useState(empty); const [saved, setSaved] = useState(false);
  const load = () => { if (!database) return; void Promise.all([createEncryptedRepository(database, dek, 'DeathCertificateRecord', deathCertificateSchema).list(), createEncryptedRepository(database, dek, 'Person', personSchema).list()]).then(([nextRecords, nextPeople]) => { setRecords(nextRecords); setPeople(nextPeople); }); };
  useEffect(load, [database, dek]);
  const save = async (event: FormEvent) => { event.preventDefault(); if (!database || !form.deceasedPersonId || !form.copiesOrdered.trim()) return; const now = new Date().toISOString(); await createEncryptedRepository(database, dek, 'DeathCertificateRecord', deathCertificateSchema).put({ id: crypto.randomUUID(), schemaVersion: 1, createdAt: now, updatedAt: now, ...form, copiesOrdered: form.copiesOrdered.trim() }); setForm(empty); setSaved(true); load(); };
  const name = (id: string) => { const person = people.find((item) => item.id === id); return person ? `${person.legalFirstName} ${person.legalLastName}` : t('deceased'); };
  return <section className="section-page v2-feature"><p className="eyebrow">{t('title')}</p><h2>{t('title')}</h2><p>{t('intro')}</p><p className="security-clarification">{t('caution')}</p><div className="section-card"><h3>{t('summary')}</h3>{records.length === 0 ? <p>{t('empty')}</p> : <ul>{records.map((record) => <li key={record.id}>{name(record.deceasedPersonId)} — {record.copiesOrdered}</li>)}</ul>}</div><div className="section-card"><h3>{t('add')}</h3><form onSubmit={(event) => void save(event)}><SelectField label={t('deceased')} value={form.deceasedPersonId} onChange={(event) => setForm({ ...form, deceasedPersonId: event.target.value })} options={[{ value: '', label: t('deceased') }, ...people.map((person) => ({ value: person.id, label: `${person.legalFirstName} ${person.legalLastName}` }))]} /><div className="form-grid"><TextField label={t('copiesOrdered')} value={form.copiesOrdered} onChange={(event) => setForm({ ...form, copiesOrdered: event.target.value })} required /><TextField label={t('orderingOffice')} value={form.orderingOffice} onChange={(event) => setForm({ ...form, orderingOffice: event.target.value })} /><TextField label={t('orderDate')} type="date" value={form.orderDate} onChange={(event) => setForm({ ...form, orderDate: event.target.value })} /><TextField label={t('copiesReceived')} value={form.copiesReceived} onChange={(event) => setForm({ ...form, copiesReceived: event.target.value })} /><TextField label={t('institution')} value={form.institution} onChange={(event) => setForm({ ...form, institution: event.target.value })} /><TextField label={t('copySent')} value={form.copySent} onChange={(event) => setForm({ ...form, copySent: event.target.value })} /><TextField label={t('returnExpected')} value={form.returnExpected} onChange={(event) => setForm({ ...form, returnExpected: event.target.value })} /><TextField label={t('referenceNumber')} value={form.referenceNumber} onChange={(event) => setForm({ ...form, referenceNumber: event.target.value })} /></div><TextArea label={t('notes')} value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /><label><input type="checkbox" checked={form.includeInPrint} onChange={(event) => setForm({ ...form, includeInPrint: event.target.checked })} /> {t('includeInPrint')}</label><label><input type="checkbox" checked={form.includeInReadableExport} onChange={(event) => setForm({ ...form, includeInReadableExport: event.target.checked })} /> {t('includeInReadableExport')}</label><button className="button button-primary">{t('save')}</button>{saved && <p role="status">{t('saved')}</p>}</form></div><div className="section-card paper-actions"><h3>{t('paperActions')}</h3><p>☐ {t('sent')}    ☐ {t('returned')}    ☐ {t('noReturnExpected')}</p><p>{t('date')}: ____ / ____ / ______    {t('initials')}: __________    {t('reference')}: __________</p></div></section>;
}
