import { useEffect, useState, type FormEvent } from 'react';
import { useTranslation } from 'react-i18next';
import { z } from 'zod';
import { SelectField, TextArea, TextField } from '../../components/forms';
import { personSchema } from '../household/HouseholdSetup';
import { createEncryptedRepository, type ContinuityDatabase } from '../../data/repositories/encryptedRepository';

const base = { id: z.string(), schemaVersion: z.number(), createdAt: z.string(), updatedAt: z.string() };
export const estateAdministrationSchema = z.object({ ...base, deceasedPersonId: z.string(), representative: z.string(), attorney: z.string(), courtAgency: z.string(), caseReference: z.string(), task: z.string(), responsiblePersonId: z.string(), supportingDocument: z.string(), targetTiming: z.string(), notes: z.string(), includeInPrint: z.boolean(), includeInReadableExport: z.boolean() });
type EstateTask = z.infer<typeof estateAdministrationSchema>; type Person = z.infer<typeof personSchema>;
const empty = { deceasedPersonId: '', representative: '', attorney: '', courtAgency: '', caseReference: '', task: '', responsiblePersonId: '', supportingDocument: '', targetTiming: '', notes: '', includeInPrint: true, includeInReadableExport: true };

export function EstateAdministrationTracker({ database, dek }: { database: ContinuityDatabase | null; dek: CryptoKey }) {
  const { t } = useTranslation('v2', { keyPrefix: 'estate_administration_tracker' });
  const [records, setRecords] = useState<EstateTask[]>([]); const [people, setPeople] = useState<Person[]>([]); const [form, setForm] = useState(empty); const [saved, setSaved] = useState(false);
  const load = () => { if (!database) return; void Promise.all([createEncryptedRepository(database, dek, 'EstateAdministrationTask', estateAdministrationSchema).list(), createEncryptedRepository(database, dek, 'Person', personSchema).list()]).then(([nextRecords, nextPeople]) => { setRecords(nextRecords); setPeople(nextPeople); }); };
  useEffect(load, [database, dek]);
  const save = async (event: FormEvent) => { event.preventDefault(); if (!database || !form.deceasedPersonId || !form.task.trim()) return; const now = new Date().toISOString(); await createEncryptedRepository(database, dek, 'EstateAdministrationTask', estateAdministrationSchema).put({ id: crypto.randomUUID(), schemaVersion: 1, createdAt: now, updatedAt: now, ...form, task: form.task.trim() }); setForm(empty); setSaved(true); load(); };
  const name = (id: string) => { const person = people.find((item) => item.id === id); return person ? `${person.legalFirstName} ${person.legalLastName}` : t('deceased'); };
  const personOptions = [{ value: '', label: t('deceased') }, ...people.map((person) => ({ value: person.id, label: `${person.legalFirstName} ${person.legalLastName}` }))];
  return <section className="section-page v2-feature"><p className="eyebrow">{t('title')}</p><h2>{t('title')}</h2><p>{t('intro')}</p><p className="security-clarification">{t('caution')}</p><div className="section-card"><h3>{t('summary')}</h3>{records.length === 0 ? <p>{t('empty')}</p> : <ul>{records.map((record) => <li key={record.id}>{name(record.deceasedPersonId)} — {record.task}</li>)}</ul>}</div><div className="section-card"><h3>{t('add')}</h3><form onSubmit={(event) => void save(event)}><div className="form-grid"><SelectField label={t('deceased')} value={form.deceasedPersonId} onChange={(event) => setForm({ ...form, deceasedPersonId: event.target.value })} options={personOptions} /><TextField label={t('representative')} value={form.representative} onChange={(event) => setForm({ ...form, representative: event.target.value })} /><TextField label={t('attorney')} value={form.attorney} onChange={(event) => setForm({ ...form, attorney: event.target.value })} /><TextField label={t('courtAgency')} value={form.courtAgency} onChange={(event) => setForm({ ...form, courtAgency: event.target.value })} /><TextField label={t('caseReference')} value={form.caseReference} onChange={(event) => setForm({ ...form, caseReference: event.target.value })} /><TextField label={t('task')} value={form.task} onChange={(event) => setForm({ ...form, task: event.target.value })} required /><SelectField label={t('responsiblePerson')} value={form.responsiblePersonId} onChange={(event) => setForm({ ...form, responsiblePersonId: event.target.value })} options={personOptions} /><TextField label={t('supportingDocument')} value={form.supportingDocument} onChange={(event) => setForm({ ...form, supportingDocument: event.target.value })} /><TextField label={t('targetTiming')} type="date" value={form.targetTiming} onChange={(event) => setForm({ ...form, targetTiming: event.target.value })} /></div><TextArea label={t('notes')} value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /><label><input type="checkbox" checked={form.includeInPrint} onChange={(event) => setForm({ ...form, includeInPrint: event.target.checked })} /> {t('includeInPrint')}</label><label><input type="checkbox" checked={form.includeInReadableExport} onChange={(event) => setForm({ ...form, includeInReadableExport: event.target.checked })} /> {t('includeInReadableExport')}</label><button className="button button-primary">{t('save')}</button>{saved && <p role="status">{t('saved')}</p>}</form></div><div className="section-card paper-actions"><h3>{t('paperActions')}</h3><p>☐ {t('notStarted')} ☐ {t('inProgress')} ☐ {t('completed')} ☐ {t('notApplicable')}</p><p>{t('date')}: ____ / ____ / ______  {t('initials')}: __________  {t('notes')}: __________________________</p></div></section>;
}
