import { useEffect, useState, type FormEvent } from 'react';
import { useTranslation } from 'react-i18next';
import { z } from 'zod';
import { SelectField, TextArea } from '../../components/forms';
import { createEncryptedRepository, type ContinuityDatabase } from '../../data/repositories/encryptedRepository';
import { personSchema } from '../household/HouseholdSetup';

const base = { id: z.string(), schemaVersion: z.number(), createdAt: z.string(), updatedAt: z.string() };
export const lifeStorySchema = z.object({
  ...base,
  personId: z.string(), childhood: z.string(), parentsFamily: z.string(), placesLived: z.string(), education: z.string(), career: z.string(), service: z.string(), relationships: z.string(), children: z.string(), turningPoints: z.string(), proudestMoments: z.string(), lessons: z.string(), favoriteMemories: z.string(), values: z.string(), messageToFamily: z.string(), supportingDocumentLocation: z.string(), primaryContact: z.string(), preparerNotes: z.string(), notes: z.string(), printPolicy: z.enum(['full', 'last4', 'hidden']), includeInPrint: z.boolean(), includeInReadableExport: z.boolean(),
});
type RecordType = z.infer<typeof lifeStorySchema>;
type Person = z.infer<typeof personSchema>;
type FormState = Omit<RecordType, 'id' | 'schemaVersion' | 'createdAt' | 'updatedAt'>;
const empty: FormState = { personId: '', childhood: '', parentsFamily: '', placesLived: '', education: '', career: '', service: '', relationships: '', children: '', turningPoints: '', proudestMoments: '', lessons: '', favoriteMemories: '', values: '', messageToFamily: '', supportingDocumentLocation: '', primaryContact: '', preparerNotes: '', notes: '', printPolicy: 'hidden', includeInPrint: true, includeInReadableExport: true };

export function LifeStoryPersonalHistory({ database, dek }: { database: ContinuityDatabase | null; dek: CryptoKey }) {
  const { t } = useTranslation('v2', { keyPrefix: 'life_story_personal_history_questionnaire' });
  const [records, setRecords] = useState<RecordType[]>([]); const [people, setPeople] = useState<Person[]>([]); const [form, setForm] = useState<FormState>(empty); const [saved, setSaved] = useState(false);
  const load = () => { if (!database) return; void Promise.all([createEncryptedRepository(database, dek, 'LifeStoryRecord', lifeStorySchema).list(), createEncryptedRepository(database, dek, 'Person', personSchema).list()]).then(([nextRecords, nextPeople]) => { setRecords(nextRecords); setPeople(nextPeople); }); };
  useEffect(load, [database, dek]);
  const name = (id: string) => { const person = people.find((item) => item.id === id); return person ? `${person.legalFirstName} ${person.legalLastName}` : t('unknown'); };
  const save = async (event: FormEvent) => { event.preventDefault(); if (!database || !form.personId) return; const now = new Date().toISOString(); await createEncryptedRepository(database, dek, 'LifeStoryRecord', lifeStorySchema).put({ id: crypto.randomUUID(), schemaVersion: 1, createdAt: now, updatedAt: now, ...form }); setForm(empty); setSaved(true); load(); };
  const personOptions = [{ value: '', label: t('personRequired') }, ...people.map((person) => ({ value: person.id, label: `${person.legalFirstName} ${person.legalLastName}` }))];
  const fields: Array<[keyof FormState, string]> = [['childhood', 'childhood'], ['parentsFamily', 'parentsFamily'], ['placesLived', 'placesLived'], ['education', 'education'], ['career', 'career'], ['service', 'service'], ['relationships', 'relationships'], ['children', 'children'], ['turningPoints', 'turningPoints'], ['proudestMoments', 'proudestMoments'], ['lessons', 'lessons'], ['favoriteMemories', 'favoriteMemories'], ['values', 'values'], ['messageToFamily', 'messageToFamily']];
  return <section className="section-page v2-feature"><p className="eyebrow">{t('title')}</p><h2>{t('title')}</h2><p>{t('intro')}</p><p className="security-clarification">{t('caution')}</p><div className="section-card"><h3>{t('summary')}</h3>{records.length === 0 ? <p>{t('empty')}</p> : <ul>{records.map((record) => <li key={record.id}>{name(record.personId)} — {record.messageToFamily || t('questionnairePrepared')}</li>)}</ul>}</div><div className="section-card"><h3>{t('add')}</h3><form onSubmit={(event) => void save(event)}><SelectField label={t('person')} value={form.personId} onChange={(event) => setForm({ ...form, personId: event.target.value })} options={personOptions} required /><div className="form-grid">{fields.map(([field, key]) => <TextArea key={field} label={t(key)} value={form[field] as string} onChange={(event) => setForm({ ...form, [field]: event.target.value })} />)}</div><TextArea label={t('supportingDocumentLocation')} value={form.supportingDocumentLocation} onChange={(event) => setForm({ ...form, supportingDocumentLocation: event.target.value })} /><TextArea label={t('primaryContact')} value={form.primaryContact} onChange={(event) => setForm({ ...form, primaryContact: event.target.value })} /><TextArea label={t('preparerNotes')} value={form.preparerNotes} onChange={(event) => setForm({ ...form, preparerNotes: event.target.value })} /><TextArea label={t('notes')} value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /><SelectField label={t('printPolicy')} value={form.printPolicy} onChange={(event) => setForm({ ...form, printPolicy: event.target.value as RecordType['printPolicy'] })} options={(['full', 'last4', 'hidden'] as const).map((value) => ({ value, label: t(value) }))} /><label><input type="checkbox" checked={form.includeInPrint} onChange={(event) => setForm({ ...form, includeInPrint: event.target.checked })} /> {t('includeInPrint')}</label><label><input type="checkbox" checked={form.includeInReadableExport} onChange={(event) => setForm({ ...form, includeInReadableExport: event.target.checked })} /> {t('includeInReadableExport')}</label><button className="button button-primary">{t('save')}</button>{saved && <p role="status">{t('saved')}</p>}</form></div><div className="section-card paper-actions"><h3>{t('paperReview')}</h3><p>☐ {t('reviewedWithFamily')}  ☐ {t('additionsRecorded')}</p><p>{t('date')}: ____ / ____ / ______  {t('initials')}: __________  {t('reference')}: ____________________</p><div className="handwriting-lines" aria-hidden="true" /></div></section>;
}
