import { expect, test } from '@playwright/test';
import { statSync } from 'node:fs';

test('prepares an AI and online service account record', async ({ page }) => {
  await page.goto('/binder/setup');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Begin Binder Setup' }).click();
  await page.getByRole('textbox', { name: 'Passphrase', exact: true }).fill('a deliberately long passphrase');
  await page.getByRole('textbox', { name: 'Confirm passphrase' }).fill('a deliberately long passphrase');
  await page.getByRole('checkbox', { name: 'I understand that Continuity Binder cannot recover this passphrase.' }).check();
  await page.getByRole('button', { name: 'Create encrypted binder' }).click();
  await page.getByRole('link', { name: 'Household Setup' }).click();
  await page.getByLabel('Household display name').fill('Synthetic household');
  await page.getByLabel('Primary adults').fill('Alex Example');
  await page.getByRole('button', { name: 'Save household setup' }).click();
  await expect(page.getByRole('status')).toContainText('Saved locally');
  await page.getByRole('link', { name: 'AI / Online Service Accounts' }).click();
  await expect(page.getByText(/No ai \/ online service accounts records/i)).toBeVisible();
  await page.getByLabel('Service').fill('AI workspace');
  await page.getByLabel('Owner/business').selectOption({ label: 'Alex Example' });
  await page.getByLabel('Purpose').fill('Projects');
  await page.getByLabel('Account identifier').fill('••••1234');
  await page.getByLabel('Credential location').fill('Password manager');
  await page.getByRole('button', { name: 'Save record locally' }).click();
  await expect(page.getByRole('status')).toContainText('Saved locally');
  await expect(page.getByText(/AI workspace — Alex Example — ••••1234/)).toBeVisible();
  await expect(page.getByText(/Continue.*Transfer.*Export data.*Cancel.*Review/)).toBeVisible();
  await page.getByRole('link', { name: 'Binder Preview' }).click();
  const section = page.locator('.binder-section-aiOnlineServices');
  await expect(section).toContainText('AI / Online Service Accounts');
  await expect(section).toContainText('☐ Continue');
  await expect(section).toContainText('••••1234');
  await expect(section.locator('.page-break')).toHaveCount(1);
  await page.emulateMedia({ media: 'print' });
  const letterPdf = test.info().outputPath('ai-online-services-letter.pdf');
  await page.pdf({ format: 'Letter', printBackground: true, path: letterPdf });
  expect(statSync(letterPdf).size).toBeGreaterThan(0);
  await page.emulateMedia({ media: 'screen' });
  await page.getByLabel('Page size').selectOption('a4');
  await page.emulateMedia({ media: 'print' });
  const a4Pdf = test.info().outputPath('ai-online-services-a4.pdf');
  await page.pdf({ format: 'A4', printBackground: true, path: a4Pdf });
  expect(statSync(a4Pdf).size).toBeGreaterThan(0);
});
