import { expect, test } from '@playwright/test';
import { statSync } from 'node:fs';

test('prepares a masked crypto and digital asset continuity record', async ({ page }) => {
  await page.goto('/binder/setup');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Begin Binder Setup' }).click();
  await page.getByRole('textbox', { name: 'Passphrase', exact: true }).fill('a deliberately long passphrase');
  await page.getByRole('textbox', { name: 'Confirm passphrase' }).fill('a deliberately long passphrase');
  await page.getByRole('checkbox', { name: 'I understand that Continuity Binder cannot recover this passphrase.' }).check();
  await page.getByRole('button', { name: 'Create encrypted binder' }).click();
  await page.getByRole('link', { name: 'Household Setup' }).click();
  await page.getByLabel('Household display name').fill('Synthetic household');
  await page.getByLabel('Primary adults').fill('Alex Example');
  await page.getByRole('button', { name: 'Save household setup' }).click();
  await expect(page.getByRole('status')).toContainText('Saved locally');
  await page.getByRole('link', { name: 'Crypto / Digital Asset Continuity Form' }).click();
  await expect(page.getByText(/No crypto \/ digital asset continuity form records/i)).toBeVisible();
  await page.getByLabel('Owner').selectOption({ label: 'Alex Example' });
  await page.getByLabel('Asset/wallet category').fill('Bitcoin wallet');
  await page.getByLabel('Custodian/exchange').fill('Exchange');
  await page.getByLabel('Account/wallet identifier masking').fill('••••1234');
  await page.getByLabel('Hardware-wallet location').fill('Safe');
  await page.getByRole('button', { name: 'Save record locally' }).click();
  await expect(page.getByRole('status')).toContainText('Saved locally');
  await expect(page.getByText(/Alex Example — Bitcoin wallet — ••••1234/)).toBeVisible();
  await expect(page.getByText(/Device located.*Recovery instructions located.*Technical\/professional contact reached/)).toBeVisible();
  await page.getByRole('link', { name: 'Binder Preview' }).click();
  const section = page.locator('.binder-section-cryptoDigitalAsset');
  await expect(section).toContainText('Crypto / Digital Asset Continuity Form');
  await expect(section).toContainText('☐ Device located');
  await expect(section).toContainText('••••1234');
  await expect(section.locator('.page-break')).toHaveCount(1);
  await page.emulateMedia({ media: 'print' });
  const letterPdf = test.info().outputPath('crypto-digital-asset-letter.pdf');
  await page.pdf({ format: 'Letter', printBackground: true, path: letterPdf });
  expect(statSync(letterPdf).size).toBeGreaterThan(0);
  await page.emulateMedia({ media: 'screen' });
  await page.getByLabel('Page size').selectOption('a4');
  await page.emulateMedia({ media: 'print' });
  const a4Pdf = test.info().outputPath('crypto-digital-asset-a4.pdf');
  await page.pdf({ format: 'A4', printBackground: true, path: a4Pdf });
  expect(statSync(a4Pdf).size).toBeGreaterThan(0);
});
