import { expect, test } from '@playwright/test';
import { statSync } from 'node:fs';

test('prepares collection facts with blank specialist workflow controls', async ({ page }) => {
  await page.goto('/binder/setup');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Begin Binder Setup' }).click();
  await page.getByRole('textbox', { name: 'Passphrase', exact: true }).fill('a deliberately long passphrase');
  await page.getByRole('textbox', { name: 'Confirm passphrase' }).fill('a deliberately long passphrase');
  await page.getByRole('checkbox', { name: 'I understand that Continuity Binder cannot recover this passphrase.' }).check();
  await page.getByRole('button', { name: 'Create encrypted binder' }).click();
  await page.getByRole('link', { name: 'Collections Inventory' }).click();
  await expect(page.getByText(/No collections inventory records/i)).toBeVisible();
  await page.getByLabel('Collection name').fill('Synthetic stamps');
  await page.getByLabel('Category').fill('Philately');
  await page.getByRole('textbox', { name: 'Location', exact: true }).fill('Study shelf');
  await page.getByRole('button', { name: 'Save record locally' }).click();
  await expect(page.getByRole('status')).toContainText('Saved locally');
  await expect(page.getByText(/Synthetic stamps — Philately — Unknown/i)).toBeVisible();
  await expect(page.getByText(/Specialist contacted.*Catalog located.*Valuation obtained/)).toBeVisible();
  await expect(page.getByText(/Do not dispose of collection items before review/i)).toBeVisible();
  await page.getByRole('link', { name: 'Binder Preview' }).click();
  const section = page.locator('.binder-section-collections');
  await expect(section).toContainText('Collections Inventory');
  await expect(section).toContainText('☐ Specialist contacted');
  await expect(section).toContainText('Do not dispose of collection items before review');
  await expect(section.locator('.page-break')).toHaveCount(1);
  await page.emulateMedia({ media: 'print' });
  const letterPdf = test.info().outputPath('collections-letter.pdf');
  await page.pdf({ format: 'Letter', printBackground: true, path: letterPdf });
  expect(statSync(letterPdf).size).toBeGreaterThan(0);
  await page.emulateMedia({ media: 'screen' });
  await page.getByLabel('Page size').selectOption('a4');
  await page.emulateMedia({ media: 'print' });
  const a4Pdf = test.info().outputPath('collections-a4.pdf');
  await page.pdf({ format: 'A4', printBackground: true, path: a4Pdf });
  expect(statSync(a4Pdf).size).toBeGreaterThan(0);
});
