import { expect, test } from '@playwright/test';
import { statSync } from 'node:fs';

test('prepares a do-not-discard record with blank survivor decisions', async ({ page }) => {
  await page.goto('/binder/setup');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Begin Binder Setup' }).click();
  await page.getByRole('textbox', { name: 'Passphrase', exact: true }).fill('a deliberately long passphrase');
  await page.getByRole('textbox', { name: 'Confirm passphrase' }).fill('a deliberately long passphrase');
  await page.getByRole('checkbox', { name: 'I understand that Continuity Binder cannot recover this passphrase.' }).check();
  await page.getByRole('button', { name: 'Create encrypted binder' }).click();
  await page.getByRole('link', { name: 'Do Not Throw This Away List' }).click();
  await expect(page.getByText(/No do not throw this away list records/i)).toBeVisible();
  await page.getByLabel('Item').fill('Synthetic archive drive');
  await page.getByRole('textbox', { name: 'Location', exact: true }).fill('Office shelf');
  await page.getByLabel('Why it matters').fill('Contains family records');
  await page.getByRole('button', { name: 'Save record locally' }).click();
  await expect(page.getByRole('status')).toContainText('Saved locally');
  await expect(page.getByText(/Synthetic archive drive — Office shelf — Unknown/i)).toBeVisible();
  await expect(page.getByText(/Located.*Reviewed.*Safe to dispose/)).toBeVisible();
  await expect(page.getByText(/Do not throw away, donate, recycle, or destroy/i)).toBeVisible();
  await page.getByRole('link', { name: 'Binder Preview' }).click();
  const section = page.locator('.binder-section-doNotThrowAway');
  await expect(section).toContainText('Do Not Throw This Away List');
  await expect(section).toContainText('☐ Located');
  await expect(section).toContainText('Do not throw away, donate, recycle, or destroy');
  await expect(section.locator('.page-break')).toHaveCount(1);
  await page.emulateMedia({ media: 'print' });
  const letterPdf = test.info().outputPath('do-not-discard-letter.pdf');
  await page.pdf({ format: 'Letter', printBackground: true, path: letterPdf });
  expect(statSync(letterPdf).size).toBeGreaterThan(0);
  await page.emulateMedia({ media: 'screen' });
  await page.getByLabel('Page size').selectOption('a4');
  await page.emulateMedia({ media: 'print' });
  const a4Pdf = test.info().outputPath('do-not-discard-a4.pdf');
  await page.pdf({ format: 'A4', printBackground: true, path: a4Pdf });
  expect(statSync(a4Pdf).size).toBeGreaterThan(0);
});
