import { expect, test } from '@playwright/test';
import { statSync } from 'node:fs';

test('prepares a family recipe with handwritten variation space', async ({ page }) => {
  await page.goto('/binder/setup');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Begin Binder Setup' }).click();
  await page.getByRole('textbox', { name: 'Passphrase', exact: true }).fill('a deliberately long passphrase');
  await page.getByRole('textbox', { name: 'Confirm passphrase' }).fill('a deliberately long passphrase');
  await page.getByRole('checkbox', { name: 'I understand that Continuity Binder cannot recover this passphrase.' }).check();
  await page.getByRole('button', { name: 'Create encrypted binder' }).click();
  await page.getByRole('link', { name: 'Family Recipes & Traditions' }).click();
  await expect(page.getByText(/No family recipes & traditions records/i)).toBeVisible();
  await page.getByLabel('Title').fill('Grandma pie');
  await page.getByLabel('Type').fill('Recipe');
  await page.getByLabel('Instructions').fill('Bake slowly.');
  await page.getByRole('button', { name: 'Save record locally' }).click();
  await expect(page.getByRole('status')).toContainText('Saved locally');
  await expect(page.getByText(/Grandma pie — Recipe — Unknown/i)).toBeVisible();
  await expect(page.getByText(/Handwritten variations.*Family notes/)).toBeVisible();
  await page.getByRole('link', { name: 'Binder Preview' }).click();
  const section = page.locator('.binder-section-recipesTraditions');
  await expect(section).toContainText('Family Recipes & Traditions');
  await expect(section).toContainText('Grandma pie');
  await expect(section).toContainText('Handwritten variations');
  await expect(section).toContainText('Family notes');
  await expect(section.locator('.page-break')).toHaveCount(1);
  await page.emulateMedia({ media: 'print' });
  const letterPdf = test.info().outputPath('family-recipes-letter.pdf');
  await page.pdf({ format: 'Letter', printBackground: true, path: letterPdf });
  expect(statSync(letterPdf).size).toBeGreaterThan(0);
  await page.emulateMedia({ media: 'screen' });
  await page.getByLabel('Page size').selectOption('a4');
  await page.emulateMedia({ media: 'print' });
  const a4Pdf = test.info().outputPath('family-recipes-a4.pdf');
  await page.pdf({ format: 'A4', printBackground: true, path: a4Pdf });
  expect(statSync(a4Pdf).size).toBeGreaterThan(0);
});
