import { expect, test } from '@playwright/test';
import { statSync } from 'node:fs';

test('prepares a government and licensing record with blank survivor actions', async ({ page }) => {
  await page.goto('/binder/setup');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Begin binder setup' }).click();
  await page.getByRole('textbox', { name: 'Passphrase', exact: true }).fill('a deliberately long passphrase');
  await page.getByRole('textbox', { name: 'Confirm passphrase' }).fill('a deliberately long passphrase');
  await page.getByRole('checkbox', { name: 'I understand that Continuity Binder cannot recover this passphrase.' }).check();
  await page.getByRole('button', { name: 'Create encrypted binder' }).click();
  await page.getByRole('link', { name: 'Household Setup' }).click();
  await page.getByLabel('Household display name').fill('Synthetic Household');
  await page.getByLabel('Primary adults').fill('Alex Example');
  await page.getByRole('button', { name: 'Save household setup' }).click();
  await expect(page.getByRole('status')).toContainText('Saved locally');
  await page.getByRole('link', { name: 'Government & Licensing Records' }).click();
  await expect(page.getByText(/No government & licensing records records/i)).toBeVisible();
  await page.getByLabel('Person/business').selectOption({ label: 'Alex Example' });
  await page.getByLabel('Credential type').fill('Synthetic permit');
  await page.getByLabel('Issuing authority').fill('Synthetic authority');
  await page.getByRole('button', { name: 'Save record locally' }).click();
  await expect(page.getByRole('status')).toContainText('Saved locally');
  await expect(page.getByText(/Synthetic permit — Synthetic authority/)).toBeVisible();
  await expect(page.getByText(/Renew.*Cancel.*Transfer.*Preserve.*Review/)).toBeVisible();
  await page.getByRole('link', { name: 'Binder Preview' }).click();
  const licensingSection = page.locator('.binder-section-governmentLicensing');
  await expect(licensingSection).toContainText('Government & Licensing Records');
  await expect(licensingSection).toContainText('☐ Renew');
  await expect(licensingSection.locator('.page-break')).toHaveCount(1);
  await page.emulateMedia({ media: 'print' });
  const letterPdf = test.info().outputPath('government-licensing-letter.pdf');
  await page.pdf({ format: 'Letter', printBackground: true, path: letterPdf });
  expect(statSync(letterPdf).size).toBeGreaterThan(0);
  await page.emulateMedia({ media: 'screen' });
  await page.getByLabel('Page size').selectOption('a4');
  await page.emulateMedia({ media: 'print' });
  const a4Pdf = test.info().outputPath('government-licensing-a4.pdf');
  await page.pdf({ format: 'A4', printBackground: true, path: a4Pdf });
  expect(statSync(a4Pdf).size).toBeGreaterThan(0);
});
