import { expect, test } from '@playwright/test';
import { statSync } from 'node:fs';

test('prepares a hardware security key inventory with masked paper controls', async ({ page }) => {
  await page.goto('/binder/setup');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Begin Binder Setup' }).click();
  await page.getByRole('textbox', { name: 'Passphrase', exact: true }).fill('a deliberately long passphrase');
  await page.getByRole('textbox', { name: 'Confirm passphrase' }).fill('a deliberately long passphrase');
  await page.getByRole('checkbox', { name: 'I understand that Continuity Binder cannot recover this passphrase.' }).check();
  await page.getByRole('button', { name: 'Create encrypted binder' }).click();
  await page.getByRole('link', { name: 'Household Setup' }).click();
  await page.getByLabel('Household display name').fill('Synthetic household');
  await page.getByLabel('Primary adults').fill('Alex Example');
  await page.getByRole('button', { name: 'Save household setup' }).click();
  await expect(page.getByRole('status')).toContainText('Saved locally');
  await page.getByRole('link', { name: 'Hardware Security Key Inventory' }).click();
  await expect(page.getByText(/No hardware security key inventory records/i)).toBeVisible();
  await page.getByLabel('Key label').fill('Primary key');
  await page.getByLabel('Owner').selectOption({ label: 'Alex Example' });
  await page.getByLabel('Make/model').fill('YubiKey 5');
  await page.getByLabel('Physical location').fill('Desk drawer');
  await page.getByLabel('Backup-key location').fill('Safe');
  await page.getByRole('button', { name: 'Save record locally' }).click();
  await expect(page.getByRole('status')).toContainText('Saved locally');
  await expect(page.getByText(/Primary key — Alex Example — Desk drawer/)).toBeVisible();
  await expect(page.getByText(/Located.*Backup located.*Services reviewed/)).toBeVisible();
  await page.getByRole('link', { name: 'Binder Preview' }).click();
  const section = page.locator('.binder-section-hardwareSecurityKeys');
  await expect(section).toContainText('Hardware Security Key Inventory');
  await expect(section).toContainText('☐ Located');
  await expect(section).toContainText('Primary key');
  await expect(section.locator('.page-break')).toHaveCount(1);
  await page.emulateMedia({ media: 'print' });
  const letterPdf = test.info().outputPath('hardware-security-keys-letter.pdf');
  await page.pdf({ format: 'Letter', printBackground: true, path: letterPdf });
  expect(statSync(letterPdf).size).toBeGreaterThan(0);
  await page.emulateMedia({ media: 'screen' });
  await page.getByLabel('Page size').selectOption('a4');
  await page.emulateMedia({ media: 'print' });
  const a4Pdf = test.info().outputPath('hardware-security-keys-a4.pdf');
  await page.pdf({ format: 'A4', printBackground: true, path: a4Pdf });
  expect(statSync(a4Pdf).size).toBeGreaterThan(0);
});
