import { expect, test } from '@playwright/test';
import { statSync } from 'node:fs';

test('prepares a loyalty points record with blank survivor actions', async ({ page }) => {
  await page.goto('/binder/setup');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Begin binder setup' }).click();
  await page.getByRole('textbox', { name: 'Passphrase', exact: true }).fill('a deliberately long passphrase');
  await page.getByRole('textbox', { name: 'Confirm passphrase' }).fill('a deliberately long passphrase');
  await page.getByRole('checkbox', { name: 'I understand that Continuity Binder cannot recover this passphrase.' }).check();
  await page.getByRole('button', { name: 'Create encrypted binder' }).click();
  await page.getByRole('link', { name: 'Household Setup' }).click();
  await page.getByLabel('Household display name').fill('Synthetic Household');
  await page.getByLabel('Primary adults').fill('Alex Example');
  await page.getByRole('button', { name: 'Save household setup' }).click();
  await page.getByRole('link', { name: 'Loyalty Points & Rewards' }).click();
  await expect(page.getByText(/No loyalty points & rewards records/i)).toBeVisible();
  await page.getByLabel('Program').fill('Synthetic airline rewards');
  await page.getByLabel('Owner').selectOption({ label: 'Alex Example' });
  await page.getByLabel('Approximate points/value').fill('Unknown');
  await page.getByRole('button', { name: 'Save record locally' }).click();
  await expect(page.getByRole('status')).toContainText('Saved locally');
  await expect(page.getByText(/Synthetic airline rewards — Alex Example — Unknown/)).toBeVisible();
  await expect(page.getByText(/Provider contacted.*Transferred\/redeemed.*Closed/)).toBeVisible();
  await page.getByRole('link', { name: 'Binder Preview' }).click();
  const loyaltySection = page.locator('.binder-section-loyaltyRewards');
  await expect(loyaltySection).toContainText('Loyalty Points & Rewards');
  await expect(loyaltySection).toContainText('☐ Provider contacted');
  await expect(loyaltySection.locator('.page-break')).toHaveCount(1);
  await page.emulateMedia({ media: 'print' });
  const letterPdf = test.info().outputPath('loyalty-points-letter.pdf');
  await page.pdf({ format: 'Letter', printBackground: true, path: letterPdf });
  expect(statSync(letterPdf).size).toBeGreaterThan(0);
  await page.emulateMedia({ media: 'screen' });
  await page.getByLabel('Page size').selectOption('a4');
  await page.emulateMedia({ media: 'print' });
  const a4Pdf = test.info().outputPath('loyalty-points-a4.pdf');
  await page.pdf({ format: 'A4', printBackground: true, path: a4Pdf });
  expect(statSync(a4Pdf).size).toBeGreaterThan(0);
});
