import { expect, test } from '@playwright/test';
import { statSync } from 'node:fs';

test('prepares a life story questionnaire with chapter writing space', async ({ page }) => {
  await page.goto('/binder/setup');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Begin Binder Setup' }).click();
  await page.getByRole('textbox', { name: 'Passphrase', exact: true }).fill('a deliberately long passphrase');
  await page.getByRole('textbox', { name: 'Confirm passphrase' }).fill('a deliberately long passphrase');
  await page.getByRole('checkbox', { name: 'I understand that Continuity Binder cannot recover this passphrase.' }).check();
  await page.getByRole('button', { name: 'Create encrypted binder' }).click();
  await page.getByRole('link', { name: 'Household Setup' }).click();
  await page.getByLabel('Household display name').fill('Synthetic household');
  await page.getByLabel('Primary adults').fill('Alex Example');
  await page.getByRole('button', { name: 'Save household setup' }).click();
  await expect(page.getByRole('status')).toContainText('Saved locally');
  await page.getByRole('link', { name: 'Life Story / Personal History Questionnaire' }).click();
  await expect(page.getByText(/No life story \/ personal history questionnaire records/i)).toBeVisible();
  await page.getByLabel('Person').selectOption({ label: 'Alex Example' });
  await page.getByLabel('Childhood').fill('Small town');
  await page.getByLabel('Message to family').fill('Love');
  await page.getByRole('button', { name: 'Save record locally' }).click();
  await expect(page.getByRole('status')).toContainText('Saved locally');
  await expect(page.getByText(/Alex Example — Love/)).toBeVisible();
  await expect(page.getByText(/Reviewed with family.*Additions recorded/)).toBeVisible();
  await page.getByRole('link', { name: 'Binder Preview' }).click();
  const section = page.locator('.binder-section-lifeStory');
  await expect(section).toContainText('Life Story / Personal History Questionnaire');
  await expect(section).toContainText('☐ Reviewed with family');
  await expect(section).toContainText('Small town');
  await expect(section.locator('.page-break')).toHaveCount(1);
  await page.emulateMedia({ media: 'print' });
  const letterPdf = test.info().outputPath('life-story-letter.pdf');
  await page.pdf({ format: 'Letter', printBackground: true, path: letterPdf });
  expect(statSync(letterPdf).size).toBeGreaterThan(0);
  await page.emulateMedia({ media: 'screen' });
  await page.getByLabel('Page size').selectOption('a4');
  await page.emulateMedia({ media: 'print' });
  const a4Pdf = test.info().outputPath('life-story-a4.pdf');
  await page.pdf({ format: 'A4', printBackground: true, path: a4Pdf });
  expect(statSync(a4Pdf).size).toBeGreaterThan(0);
});
