import { expect, test } from '@playwright/test';
import { statSync } from 'node:fs';

test('prepares a personal possession story with blank paper confirmations', async ({ page }) => {
  await page.goto('/binder/setup');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Begin Binder Setup' }).click();
  await page.getByRole('textbox', { name: 'Passphrase', exact: true }).fill('a deliberately long passphrase');
  await page.getByRole('textbox', { name: 'Confirm passphrase' }).fill('a deliberately long passphrase');
  await page.getByRole('checkbox', { name: 'I understand that Continuity Binder cannot recover this passphrase.' }).check();
  await page.getByRole('button', { name: 'Create encrypted binder' }).click();
  await page.getByRole('link', { name: 'Personal Possessions With Stories' }).click();
  await expect(page.getByText(/No personal possessions with stories records/i)).toBeVisible();
  await page.getByLabel('Item reference').fill('Wooden clock');
  await page.getByLabel('Story title').fill('Grandfather clock');
  await page.getByLabel('Narrative').fill('A long family story.');
  await page.getByRole('button', { name: 'Save record locally' }).click();
  await expect(page.getByRole('status')).toContainText('Saved locally');
  await expect(page.getByText(/Grandfather clock — Wooden clock — Unknown/i)).toBeVisible();
  await expect(page.getByText(/Story reviewed.*Recipient confirmed/)).toBeVisible();
  await page.getByRole('link', { name: 'Binder Preview' }).click();
  const section = page.locator('.binder-section-personalStories');
  await expect(section).toContainText('Personal Possessions With Stories');
  await expect(section).toContainText('☐ Story reviewed');
  await expect(section).toContainText('Grandfather clock');
  await expect(section.locator('.page-break')).toHaveCount(1);
  await page.emulateMedia({ media: 'print' });
  const letterPdf = test.info().outputPath('personal-stories-letter.pdf');
  await page.pdf({ format: 'Letter', printBackground: true, path: letterPdf });
  expect(statSync(letterPdf).size).toBeGreaterThan(0);
  await page.emulateMedia({ media: 'screen' });
  await page.getByLabel('Page size').selectOption('a4');
  await page.emulateMedia({ media: 'print' });
  const a4Pdf = test.info().outputPath('personal-stories-a4.pdf');
  await page.pdf({ format: 'A4', printBackground: true, path: a4Pdf });
  expect(statSync(a4Pdf).size).toBeGreaterThan(0);
});
