import { expect, test } from '@playwright/test';
import { statSync } from 'node:fs';

test('prepares a no-value item with blank survivor disposition controls', async ({ page }) => {
  await page.goto('/binder/setup');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Begin Binder Setup' }).click();
  await page.getByRole('textbox', { name: 'Passphrase', exact: true }).fill('a deliberately long passphrase');
  await page.getByRole('textbox', { name: 'Confirm passphrase' }).fill('a deliberately long passphrase');
  await page.getByRole('checkbox', { name: 'I understand that Continuity Binder cannot recover this passphrase.' }).check();
  await page.getByRole('button', { name: 'Create encrypted binder' }).click();
  await page.getByRole('link', { name: 'These Things Have No Value List' }).click();
  await expect(page.getByText(/No these things have no value list records/i)).toBeVisible();
  await page.getByLabel('Item/category').fill('Old cables');
  await page.getByRole('textbox', { name: 'Location', exact: true }).fill('Garage');
  await page.getByLabel('Reason').fill('Replaced equipment');
  await page.getByRole('button', { name: 'Save record locally' }).click();
  await expect(page.getByRole('status')).toContainText('Saved locally');
  await expect(page.getByText(/Old cables — Garage — Unknown/i)).toBeVisible();
  await expect(page.getByText(/Reviewed.*Disposed\/donated/)).toBeVisible();
  await expect(page.getByText(/Personal note only; this is not an appraisal/i)).toBeVisible();
  await page.getByRole('link', { name: 'Binder Preview' }).click();
  const section = page.locator('.binder-section-noValueDisposable');
  await expect(section).toContainText('These Things Have No Value List');
  await expect(section).toContainText('☐ Reviewed');
  await expect(section).toContainText('Personal note only; this is not an appraisal');
  await expect(section.locator('.page-break')).toHaveCount(1);
  await page.emulateMedia({ media: 'print' });
  const letterPdf = test.info().outputPath('no-value-letter.pdf');
  await page.pdf({ format: 'Letter', printBackground: true, path: letterPdf });
  expect(statSync(letterPdf).size).toBeGreaterThan(0);
  await page.emulateMedia({ media: 'screen' });
  await page.getByLabel('Page size').selectOption('a4');
  await page.emulateMedia({ media: 'print' });
  const a4Pdf = test.info().outputPath('no-value-a4.pdf');
  await page.pdf({ format: 'A4', printBackground: true, path: a4Pdf });
  expect(statSync(a4Pdf).size).toBeGreaterThan(0);
});
