import { useState } from 'react';
import { Link, Navigate, Outlet, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { LanguageSelector } from './i18n/LanguageSelector';

const navigation = [
  ['overview', 'overview'], ['householdSetup', 'household-setup'], ['peopleContacts', 'people-contacts'],
  ['legalEstate', 'legal-estate'], ['moneyBenefits', 'money-benefits'], ['property', 'property'],
  ['digitalAccess', 'digital-access'], ['familyContinuity', 'family-continuity'], ['taxRecords', 'tax-records'],
  ['wishesLegacy', 'wishes-legacy'], ['review', 'review'], ['preview', 'preview'], ['export', 'export'],
  ['backupRestore', 'backup-restore'], ['settings', 'settings/security'],
] as const;

function PublicPage({ titleKey }: { titleKey: 'privacy' | 'security' | 'terms' | 'notFound' }) { const { t } = useTranslation(); return <main className="public-page"><Link to="/">{t('backToApp')}</Link><h1>{t(titleKey)}</h1><p>{t('tagline')}</p></main>; }
function Landing() { const { t } = useTranslation(['common', 'landing']); return <><header className="site-header"><Link className="wordmark" to="/"><span>{t('appName')}</span><small>{t('localFirst')}</small></Link><LanguageSelector /><nav aria-label={t('primary', { ns: 'navigation' })}><a href="#privacy">{t('privacy')}</a><a href="#how-it-works">{t('howItWorks')}</a></nav></header><main><section className="hero"><p className="eyebrow">{t('eyebrow', { ns: 'landing' })}</p><h1>{t('headline', { ns: 'landing' })}</h1><p className="hero-copy">{t('description', { ns: 'landing' })}</p><p className="trust-statement">{t('trust', { ns: 'landing' })}</p><Link className="button button-primary" to="/binder/setup">{t('cta', { ns: 'landing' })}</Link><p className="free-note">{t('freeNote', { ns: 'landing' })}</p><p className="quiet-note">{t('quietNote', { ns: 'landing' })}</p></section><section className="trust-strip" id="privacy" aria-label={t('privacy')}><article><h2>{t('localTitle', { ns: 'landing' })}</h2><p>{t('localBody', { ns: 'landing' })}</p></article><article><h2>{t('encryptedTitle', { ns: 'landing' })}</h2><p>{t('encryptedBody', { ns: 'landing' })}</p></article><article><h2>{t('noTrackingTitle', { ns: 'landing' })}</h2><p>{t('noTrackingBody', { ns: 'landing' })}</p></article></section><section className="how-it-works" id="how-it-works"><h2>{t('howTitle', { ns: 'landing' })}</h2><div className="steps"><article><h3>{t('stepOneTitle', { ns: 'landing' })}</h3><p>{t('stepOneBody', { ns: 'landing' })}</p></article><article><h3>{t('stepTwoTitle', { ns: 'landing' })}</h3><p>{t('stepTwoBody', { ns: 'landing' })}</p></article><article><h3>{t('stepThreeTitle', { ns: 'landing' })}</h3><p>{t('stepThreeBody', { ns: 'landing' })}</p></article></div></section><section className="security-clarification"><h2>{t('clarificationTitle', { ns: 'landing' })}</h2><p>{t('clarificationBody', { ns: 'landing' })}</p></section></main></>; }
function Setup() { const navigate = useNavigate(); const { t } = useTranslation(); return <main className="public-page"><p className="eyebrow">{t('appName')}</p><h1>{t('setupTitle')}</h1><p>{t('setupBody')}</p><button className="button button-primary" onClick={() => navigate('/binder/unlock')}>{t('continue')}</button></main>; }
function Unlock({ onUnlock }: { onUnlock: () => void }) { const navigate = useNavigate(); const { t } = useTranslation(); return <main className="public-page"><p className="eyebrow">{t('appName')}</p><h1>{t('unlockTitle')}</h1><p>{t('unlockBody')}</p><button className="button button-primary" onClick={() => { onUnlock(); navigate('/binder/overview'); }}>{t('unlock')}</button></main>; }
function Shell({ onLock }: { onLock: () => void }) { const location = useLocation(); const { t } = useTranslation(); const titleKey = navigation.find(([, path]) => location.pathname.endsWith(path))?.[0] ?? 'overview'; return <div className="app-layout"><a className="skip-link" href="#main-content">{t('skipToContent')}</a><aside className="sidebar"><Link className="wordmark" to="/binder/overview"><span>{t('appName')}</span><small>{t('localFirst')}</small></Link><LanguageSelector /><p className="security-indicator">{t('unlockedOnDevice')}</p><nav aria-label={t('binder', { ns: 'navigation' })}>{navigation.map(([key, path]) => <Link className={location.pathname.endsWith(path) ? 'active' : ''} key={path} to={`/binder/${path}`}>{t(key, { ns: 'navigation' })}</Link>)}</nav></aside><section className="content-region"><header className="utility-bar"><h1>{t(titleKey, { ns: 'navigation' })}</h1><span className="save-state">{t('savedLocally')}</span><button className="lock-button" onClick={onLock}>{t('lock')}</button></header><main id="main-content" className="page-content"><Outlet /></main></section></div>; }
function ProtectedPage() { const location = useLocation(); const { t } = useTranslation(); const key = navigation.find(([, path]) => location.pathname.endsWith(path))?.[0] ?? 'overview'; return <section><p className="eyebrow">{t('appName')}</p><h2>{t(key, { ns: 'navigation' })}</h2><p>{t('protectedBody')}</p></section>; }

export function App() { const [unlocked, setUnlocked] = useState(false); return <Routes><Route path="/" element={<Landing />} /><Route path="/privacy" element={<PublicPage titleKey="privacy" />} /><Route path="/security" element={<PublicPage titleKey="security" />} /><Route path="/disclaimer" element={<PublicPage titleKey="terms" />} /><Route path="/binder/setup" element={<Setup />} /><Route path="/binder/unlock" element={<Unlock onUnlock={() => setUnlocked(true)} />} /><Route path="/binder" element={unlocked ? <Shell onLock={() => setUnlocked(false)} /> : <Navigate to="/binder/unlock" replace />}><Route index element={<Navigate to="overview" replace />} />{navigation.map(([, path]) => <Route key={path} path={path} element={<ProtectedPage />} />)}</Route><Route path="*" element={<PublicPage titleKey="notFound" />} /></Routes>; }
